__ROOT__=$(dirname $0)
echo "INFO: preparing $(basename $__ROOT__) jobs for $LOG"
for script in $(ls $__ROOT__/*);do
    [[ $(basename $script) = $(basename $0) ]] && continue
    sname=$(basename $script)
    [[ -z $SCRIPT_OVERRIDE ]] || [[ $SCRIPT_OVERRIDE = ${sname%*.sh} ]] || continue
    jobpath=$JOBS_DEFS_DIR/$(uuidgen)
    mkdir $jobpath
    declare -x > $jobpath/run.sh
cat << EOF >> $jobpath/run.sh
# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT
__SCRIPT_NAME__=$(basename $script| sed -r 's/[0-9]+-(.+)\.sh/\1/'| tr '-' '_')
__SCRIPT_MODULE_NAME__=$(basename $(dirname $script))
. \$SCRIPT_ROOT/lib/helpers.sh
. $script
SCRIPT_HEADER
main
SCRIPT_FOOTER
EOF
    chmod +x $jobpath/run.sh
done
wait
